### ISSUE TITLE
docker run fails

### ISSUE THREAD

**Issue by borzoj** [titanium-codes/docker-swagger-php#3]
the latest release of the container it fails to start with this error
```
sh: can't open '/docker-entrypoint.sh'
```

**Comment by rakshazi** [comment]
Could you post full command and log, please.
BTW, check #2

**Comment by borzoj** [comment]
```
$ docker run -v /var/dev/mercari-mini-uk/workspace/mercari-api-uk:/app -it --user 1000:1000 tico/swagger-php  --output /app/tool/dev/swagger/spec.json /app/app/
sh: can't open '/docker-entrypoint.sh'
$ docker ps -a | grep swagger
892ac4d8d36a        tico/swagger-php                                   "/docker-entrypoint.…"   3 seconds ago        Exited (2) 2 seconds ago                            happy_cori
...

$ docker logs -f happy_cori
sh: can't open '/docker-entrypoint.sh'
```

**Comment by rakshazi** [comment]
The problem is `--user 1000:1000`, it will work without that argument.

That docker image uses default `root` user to avoid `permission denied` error on parsing php files. If you have any other workaround (to avoid `root` user) for that - send a PR, please.

Do you have anything to add or we can close the issue?

**Comment by borzoj** [comment]
thank you
